live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x928374"
blue = "0x076678"
cyan = "0x427b58"
green = "0x79740e"
magenta = "0x8f3f71"
red = "0x9d0006"
white = "0x3c3836"
yellow = "0xb57614"

[colors.normal]
black = "0xfbf1c7"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0x7c6f64"
yellow = "0xd79921"

[colors.primary]
background = "0xf9f5d7"
foreground = "0x3c3836"

[colors.cursor]
cursor = "0x4ced4c"
# style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "L"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = '([0-9a-f]{7,128})|([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})|(i-[0-9a-f]{17})'

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0011:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011:"
key = "Semicolon"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011X"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011o"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011\u000F"
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00111"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00112"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00113"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00114"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00115"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00116"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00116"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00117"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00119"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011p"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0011n"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0011w"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011L"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011\b"
key = "Comma"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011\f"
key = "Period"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011["
key = "LBracket"
mods = "Command"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
option_as_alt = "Both"

[window.padding]
x = 2
y = 0
